server: 
  port: 7001  
   
spring: 
  profiles: dev
  application:
    name: mallcolud-config-eureka
    
eureka: 
  instance: 
    hostname: 127.0.0.1 #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
---
server: 
  port: 7001  
   
spring: 
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: 127.0.0.1 #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/